// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: shard.proto

package shard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShardPingPong_Ping_FullMethodName = "/shard.ShardPingPong/Ping"
)

// ShardPingPongClient is the client API for ShardPingPong service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardPingPongClient interface {
	Ping(ctx context.Context, in *ShardPing, opts ...grpc.CallOption) (*ShardPong, error)
}

type shardPingPongClient struct {
	cc grpc.ClientConnInterface
}

func NewShardPingPongClient(cc grpc.ClientConnInterface) ShardPingPongClient {
	return &shardPingPongClient{cc}
}

func (c *shardPingPongClient) Ping(ctx context.Context, in *ShardPing, opts ...grpc.CallOption) (*ShardPong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShardPong)
	err := c.cc.Invoke(ctx, ShardPingPong_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardPingPongServer is the server API for ShardPingPong service.
// All implementations must embed UnimplementedShardPingPongServer
// for forward compatibility.
type ShardPingPongServer interface {
	Ping(context.Context, *ShardPing) (*ShardPong, error)
	mustEmbedUnimplementedShardPingPongServer()
}

// UnimplementedShardPingPongServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardPingPongServer struct{}

func (UnimplementedShardPingPongServer) Ping(context.Context, *ShardPing) (*ShardPong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedShardPingPongServer) mustEmbedUnimplementedShardPingPongServer() {}
func (UnimplementedShardPingPongServer) testEmbeddedByValue()                       {}

// UnsafeShardPingPongServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardPingPongServer will
// result in compilation errors.
type UnsafeShardPingPongServer interface {
	mustEmbedUnimplementedShardPingPongServer()
}

func RegisterShardPingPongServer(s grpc.ServiceRegistrar, srv ShardPingPongServer) {
	// If the following call pancis, it indicates UnimplementedShardPingPongServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShardPingPong_ServiceDesc, srv)
}

func _ShardPingPong_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardPing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardPingPongServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardPingPong_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardPingPongServer).Ping(ctx, req.(*ShardPing))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardPingPong_ServiceDesc is the grpc.ServiceDesc for ShardPingPong service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardPingPong_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shard.ShardPingPong",
	HandlerType: (*ShardPingPongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ShardPingPong_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shard.proto",
}
