// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: shard.proto

package shard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenBucket   map[uint64]uint32      `protobuf:"bytes,1,rep,name=TokenBucket,proto3" json:"TokenBucket,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ServerUID     []uint64               `protobuf:"varint,2,rep,packed,name=ServerUID,proto3" json:"ServerUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardPing) Reset() {
	*x = ShardPing{}
	mi := &file_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardPing) ProtoMessage() {}

func (x *ShardPing) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardPing.ProtoReflect.Descriptor instead.
func (*ShardPing) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{0}
}

func (x *ShardPing) GetTokenBucket() map[uint64]uint32 {
	if x != nil {
		return x.TokenBucket
	}
	return nil
}

func (x *ShardPing) GetServerUID() []uint64 {
	if x != nil {
		return x.ServerUID
	}
	return nil
}

type ShardPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenBucket   map[uint64]uint32      `protobuf:"bytes,1,rep,name=TokenBucket,proto3" json:"TokenBucket,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ServerUID     []uint64               `protobuf:"varint,2,rep,packed,name=ServerUID,proto3" json:"ServerUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardPong) Reset() {
	*x = ShardPong{}
	mi := &file_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardPong) ProtoMessage() {}

func (x *ShardPong) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardPong.ProtoReflect.Descriptor instead.
func (*ShardPong) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{1}
}

func (x *ShardPong) GetTokenBucket() map[uint64]uint32 {
	if x != nil {
		return x.TokenBucket
	}
	return nil
}

func (x *ShardPong) GetServerUID() []uint64 {
	if x != nil {
		return x.ServerUID
	}
	return nil
}

var File_shard_proto protoreflect.FileDescriptor

const file_shard_proto_rawDesc = "" +
	"\n" +
	"\vshard.proto\x12\x05shard\"\xae\x01\n" +
	"\tShardPing\x12C\n" +
	"\vTokenBucket\x18\x01 \x03(\v2!.shard.ShardPing.TokenBucketEntryR\vTokenBucket\x12\x1c\n" +
	"\tServerUID\x18\x02 \x03(\x04R\tServerUID\x1a>\n" +
	"\x10TokenBucketEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xae\x01\n" +
	"\tShardPong\x12C\n" +
	"\vTokenBucket\x18\x01 \x03(\v2!.shard.ShardPong.TokenBucketEntryR\vTokenBucket\x12\x1c\n" +
	"\tServerUID\x18\x02 \x03(\x04R\tServerUID\x1a>\n" +
	"\x10TokenBucketEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x012;\n" +
	"\rShardPingPong\x12*\n" +
	"\x04Ping\x12\x10.shard.ShardPing\x1a\x10.shard.ShardPongB(Z&github.com/PxnPub/pxnMetrics/api/shardb\x06proto3"

var (
	file_shard_proto_rawDescOnce sync.Once
	file_shard_proto_rawDescData []byte
)

func file_shard_proto_rawDescGZIP() []byte {
	file_shard_proto_rawDescOnce.Do(func() {
		file_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shard_proto_rawDesc), len(file_shard_proto_rawDesc)))
	})
	return file_shard_proto_rawDescData
}

var file_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shard_proto_goTypes = []any{
	(*ShardPing)(nil), // 0: shard.ShardPing
	(*ShardPong)(nil), // 1: shard.ShardPong
	nil,               // 2: shard.ShardPing.TokenBucketEntry
	nil,               // 3: shard.ShardPong.TokenBucketEntry
}
var file_shard_proto_depIdxs = []int32{
	2, // 0: shard.ShardPing.TokenBucket:type_name -> shard.ShardPing.TokenBucketEntry
	3, // 1: shard.ShardPong.TokenBucket:type_name -> shard.ShardPong.TokenBucketEntry
	0, // 2: shard.ShardPingPong.Ping:input_type -> shard.ShardPing
	1, // 3: shard.ShardPingPong.Ping:output_type -> shard.ShardPong
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shard_proto_init() }
func file_shard_proto_init() {
	if File_shard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shard_proto_rawDesc), len(file_shard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shard_proto_goTypes,
		DependencyIndexes: file_shard_proto_depIdxs,
		MessageInfos:      file_shard_proto_msgTypes,
	}.Build()
	File_shard_proto = out.File
	file_shard_proto_goTypes = nil
	file_shard_proto_depIdxs = nil
}
