// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: front.proto

package front

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebFrontAPI_FetchStatusJSON_FullMethodName = "/front.WebFrontAPI/FetchStatusJSON"
)

// WebFrontAPIClient is the client API for WebFrontAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebFrontAPIClient interface {
	FetchStatusJSON(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusJSON, error)
}

type webFrontAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewWebFrontAPIClient(cc grpc.ClientConnInterface) WebFrontAPIClient {
	return &webFrontAPIClient{cc}
}

func (c *webFrontAPIClient) FetchStatusJSON(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusJSON, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusJSON)
	err := c.cc.Invoke(ctx, WebFrontAPI_FetchStatusJSON_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebFrontAPIServer is the server API for WebFrontAPI service.
// All implementations must embed UnimplementedWebFrontAPIServer
// for forward compatibility.
type WebFrontAPIServer interface {
	FetchStatusJSON(context.Context, *Empty) (*StatusJSON, error)
	mustEmbedUnimplementedWebFrontAPIServer()
}

// UnimplementedWebFrontAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebFrontAPIServer struct{}

func (UnimplementedWebFrontAPIServer) FetchStatusJSON(context.Context, *Empty) (*StatusJSON, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchStatusJSON not implemented")
}
func (UnimplementedWebFrontAPIServer) mustEmbedUnimplementedWebFrontAPIServer() {}
func (UnimplementedWebFrontAPIServer) testEmbeddedByValue()                     {}

// UnsafeWebFrontAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebFrontAPIServer will
// result in compilation errors.
type UnsafeWebFrontAPIServer interface {
	mustEmbedUnimplementedWebFrontAPIServer()
}

func RegisterWebFrontAPIServer(s grpc.ServiceRegistrar, srv WebFrontAPIServer) {
	// If the following call pancis, it indicates UnimplementedWebFrontAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebFrontAPI_ServiceDesc, srv)
}

func _WebFrontAPI_FetchStatusJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebFrontAPIServer).FetchStatusJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebFrontAPI_FetchStatusJSON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebFrontAPIServer).FetchStatusJSON(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WebFrontAPI_ServiceDesc is the grpc.ServiceDesc for WebFrontAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebFrontAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "front.WebFrontAPI",
	HandlerType: (*WebFrontAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchStatusJSON",
			Handler:    _WebFrontAPI_FetchStatusJSON_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "front.proto",
}
