// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: front.proto

package front

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_front_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_front_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_front_proto_rawDescGZIP(), []int{0}
}

type StatusJSON struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusJSON) Reset() {
	*x = StatusJSON{}
	mi := &file_front_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusJSON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusJSON) ProtoMessage() {}

func (x *StatusJSON) ProtoReflect() protoreflect.Message {
	mi := &file_front_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusJSON.ProtoReflect.Descriptor instead.
func (*StatusJSON) Descriptor() ([]byte, []int) {
	return file_front_proto_rawDescGZIP(), []int{1}
}

func (x *StatusJSON) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_front_proto protoreflect.FileDescriptor

const file_front_proto_rawDesc = "" +
	"\n" +
	"\vfront.proto\x12\x05front\"\a\n" +
	"\x05Empty\" \n" +
	"\n" +
	"StatusJSON\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json2A\n" +
	"\vWebFrontAPI\x122\n" +
	"\x0fFetchStatusJSON\x12\f.front.Empty\x1a\x11.front.StatusJSONB(Z&github.com/PxnPub/pxnMetrics/api/frontb\x06proto3"

var (
	file_front_proto_rawDescOnce sync.Once
	file_front_proto_rawDescData []byte
)

func file_front_proto_rawDescGZIP() []byte {
	file_front_proto_rawDescOnce.Do(func() {
		file_front_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_front_proto_rawDesc), len(file_front_proto_rawDesc)))
	})
	return file_front_proto_rawDescData
}

var file_front_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_front_proto_goTypes = []any{
	(*Empty)(nil),      // 0: front.Empty
	(*StatusJSON)(nil), // 1: front.StatusJSON
}
var file_front_proto_depIdxs = []int32{
	0, // 0: front.WebFrontAPI.FetchStatusJSON:input_type -> front.Empty
	1, // 1: front.WebFrontAPI.FetchStatusJSON:output_type -> front.StatusJSON
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_front_proto_init() }
func file_front_proto_init() {
	if File_front_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_front_proto_rawDesc), len(file_front_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_front_proto_goTypes,
		DependencyIndexes: file_front_proto_depIdxs,
		MessageInfos:      file_front_proto_msgTypes,
	}.Build()
	File_front_proto = out.File
	file_front_proto_goTypes = nil
	file_front_proto_depIdxs = nil
}
